apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reverie
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "truth-ip"
    networking.gke.io/managed-certificates: "truth-cert"
spec:
  defaultBackend:
    service:
      name: reverie
      port:
        number: 80
